version: '3.8'

services:
  # PostgreSQL Database
  stock-postgres:
    image: postgres:16-alpine
    container_name: tosserp-stock-postgres
    environment:
      POSTGRES_DB: tosserp_stock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - stock-postgres-data:/var/lib/postgresql/data
    networks:
      - toss-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  stock-redis:
    image: redis:7-alpine
    container_name: tosserp-stock-redis
    ports:
      - "6379:6379"
    volumes:
      - stock-redis-data:/data
    networks:
      - toss-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ Message Broker
  stock-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: tosserp-stock-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - stock-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - toss-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Gateway
  gateway:
    build:
      context: ./src/Gateway
      dockerfile: Dockerfile
    container_name: tosserp-gateway
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - stock-postgres
      - stock-redis
      - stock-rabbitmq
    networks:
      - toss-network

  # Mobile Client (Flutter Web)
  mobile-client:
    build:
      context: ./src/clients/mobile
      dockerfile: Dockerfile
    container_name: tosserp-mobile-client
    ports:
      - "3000:80"
    networks:
      - toss-network
    depends_on:
      - gateway

  # Web Client (Nuxt.js) - Includes admin functionality
  web-client:
    build:
      context: ./src/clients/web
      dockerfile: Dockerfile
    container_name: tosserp-web-client
    ports:
      - "80:80"
    networks:
      - toss-network
    depends_on:
      - gateway

volumes:
  stock-postgres-data:
  stock-redis-data:
  stock-rabbitmq-data:

networks:
  toss-network:
    driver: bridge
