using TossErp.Stock.Domain.Entities;
using TossErp.Stock.Domain.Common;

namespace TossErp.Stock.Domain.Events;

public record ItemQualityInspectionParameterCreatedEvent(ItemQualityInspectionParameter Parameter) : IDomainEvent;
public record ItemQualityInspectionParameterUpdatedEvent(ItemQualityInspectionParameter Parameter) : IDomainEvent;
public record ItemQualityInspectionParameterResultUpdatedEvent(ItemQualityInspectionParameter Parameter) : IDomainEvent;
public record ItemQualityInspectionParameterDeactivatedEvent(ItemQualityInspectionParameter Parameter) : IDomainEvent;
public record ItemQualityInspectionParameterActivatedEvent(ItemQualityInspectionParameter Parameter) : IDomainEvent;
public record ItemQualityInspectionParameterDeletedEvent(ItemQualityInspectionParameter Parameter) : IDomainEvent; 
