using TossErp.Stock.Domain.Entities;
using TossErp.Stock.Domain.Common;

namespace TossErp.Stock.Domain.Events;

public record ProductWarehouseInventoryCreatedEvent(ProductWarehouseInventory ProductWarehouseInventory) : IDomainEvent;
public record ProductWarehouseInventoryUpdatedEvent(ProductWarehouseInventory ProductWarehouseInventory) : IDomainEvent;
public record ProductWarehouseInventoryReservedUpdatedEvent(ProductWarehouseInventory ProductWarehouseInventory) : IDomainEvent;
public record ProductWarehouseInventoryDeactivatedEvent(ProductWarehouseInventory ProductWarehouseInventory) : IDomainEvent;
public record ProductWarehouseInventoryActivatedEvent(ProductWarehouseInventory ProductWarehouseInventory) : IDomainEvent;
public record ProductWarehouseInventoryDeletedEvent(ProductWarehouseInventory ProductWarehouseInventory) : IDomainEvent; 
