version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: tosserp-postgres
    environment:
      POSTGRES_DB: tosserp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tosserp-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: tosserp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - tosserp-network

  # TOSS ERP API
  tosserp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tosserp-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=tosserp;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tosserp-network
    restart: unless-stopped

  # TOSS Web Admin
  tosserp-web:
    build:
      context: ../toss-web
      dockerfile: Dockerfile
    container_name: tosserp-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://tosserp-api:8080
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:5000
    depends_on:
      - tosserp-api
    networks:
      - tosserp-network
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:

networks:
  tosserp-network:
    driver: bridge

