apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-processor
  namespace: tosserp
  labels:
    app: stock-processor
    version: v1.0.0
    component: stock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-processor
  template:
    metadata:
      labels:
        app: stock-processor
        version: v1.0.0
        component: stock
    spec:
      containers:
      - name: stock-processor
        image: tosserp/stock-processor:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: stock-db-secret
              key: connection-string
        - name: ConnectionStrings__EventBus
          valueFrom:
            secretKeyRef:
              name: eventbus-secret
              key: connection-string
        - name: Stock__Processor__LowStockAlert__Enabled
          value: "true"
        - name: Stock__Processor__LowStockAlert__CheckIntervalMinutes
          value: "15"
        - name: Stock__Processor__Reconciliation__Enabled
          value: "true"
        - name: Stock__Processor__Reconciliation__CheckIntervalHours
          value: "24"
        - name: Stock__Processor__Processing__Enabled
          value: "true"
        - name: Stock__Processor__Processing__BatchSize
          value: "100"
        - name: Stock__Processor__Processing__MaxRetries
          value: "3"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
      - name: docker-registry-secret
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: stock-processor-service
  namespace: tosserp
  labels:
    app: stock-processor
    component: stock
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: stock-processor
