global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using Crm.Domain.Entities;
global using Crm.Application.Interfaces;
