// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ai/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/chat.post').default>>>>
    }
    '/api/analytics/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analytics/dashboard.get').default>>>>
    }
    '/api/analytics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analytics/index.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/communication/conversations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communication/conversations/index.get').default>>>>
    }
    '/api/communication/messages/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communication/messages/send.post').default>>>>
    }
    '/api/customers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/index.post').default>>>>
    }
    '/api/dashboard/outcomes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/outcomes.get').default>>>>
    }
    '/api/debug/tenant': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug/tenant.get').default>>>>
    }
    '/api/group-buying': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/group-buying/index.get').default>>>>
    }
    '/api/group-buying/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/group-buying/join.post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/inventory/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/[id].get').default>>>>
    }
    '/api/inventory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/index.post').default>>>>
    }
    '/api/inventory/movements': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/movements.post').default>>>>
    }
    '/api/logistics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logistics/index.get').default>>>>
    }
    '/api/logistics/track/:trackingNumber': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logistics/track/[trackingNumber].get').default>>>>
    }
    '/api/manufacturing/production-orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manufacturing/production-orders/index.get').default>>>>
    }
    '/api/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/index.get').default>>>>
    }
    '/api/notifications/mark-read': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/mark-read.post').default>>>>
    }
    '/api/onboarding/setup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/onboarding/setup.post').default>>>>
    }
    '/api/projects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/index.post').default>>>>
    }
    '/api/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/index.post').default>>>>
    }
    '/api/services/analytics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/services/analytics.get').default>>>>
    }
    '/api/services/catalog': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/services/catalog.get').default>>>>
    }
    '/api/services/execute': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/services/execute.post').default>>>>
    }
    '/api/services/manage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/services/manage.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}