version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: tosserp-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - tosserp-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Optional: Add Redis for caching if needed
  redis:
    image: redis:7-alpine
    container_name: tosserp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tosserp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
  redis_data:

networks:
  tosserp-network:
    driver: bridge
