// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25/8/2025, 17:42:41
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/components/icons/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/plugins/**/*.{js,ts,mjs}","C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/composables/**/*.{js,ts,mjs}","C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/utils/**/*.{js,ts,mjs}","C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROBOOK/source/repos/Toss-Online-Services/TossErp/toss-web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;