apiVersion: v2
name: toss-platform
description: TOSS Service-as-Software Platform - Multi-tenant enterprise solution
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://toss.example.com
sources:
  - https://github.com/toss-organization/toss-platform
maintainers:
  - name: TOSS Platform Team
    email: platform@toss.example.com
keywords:
  - service-as-software
  - multi-tenant
  - ai-platform
  - enterprise
annotations:
  category: Enterprise Platform
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 23.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
  - name: jaeger
    version: 0.x.x
    repository: https://jaegertracing.github.io/helm-charts
    condition: monitoring.jaeger.enabled
  - name: istio-base
    version: 1.x.x
    repository: https://istio-release.storage.googleapis.com/charts
    condition: serviceMesh.istio.enabled
  - name: istiod
    version: 1.x.x
    repository: https://istio-release.storage.googleapis.com/charts
    condition: serviceMesh.istio.enabled
