apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: toss-ai-secrets
  namespace: toss-ai
  labels:
    app: toss-ai
    component: secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "$(AZURE_CLIENT_ID)"
    keyvaultName: "toss-keyvault-${var.environment}"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: azure-cognitive-services-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: azure-openai-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: redis-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: jwt-signing-key
          objectType: secret
          objectVersion: ""
    tenantId: "$(AZURE_TENANT_ID)"
  secretObjects:
  - secretName: toss-ai-secrets
    type: Opaque
    data:
    - objectName: azure-cognitive-services-key
      key: azure-cognitive-services-key
    - objectName: azure-openai-key
      key: azure-openai-key
    - objectName: postgres-password
      key: postgres-password
    - objectName: redis-password
      key: redis-password
    - objectName: jwt-signing-key
      key: jwt-signing-key

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: toss-data-secrets
  namespace: toss-data
  labels:
    app: toss-data
    component: secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "$(AZURE_CLIENT_ID)"
    keyvaultName: "toss-keyvault-${var.environment}"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: postgres-admin-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-replication-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: redis-admin-password
          objectType: secret
          objectVersion: ""
    tenantId: "$(AZURE_TENANT_ID)"
  secretObjects:
  - secretName: toss-data-secrets
    type: Opaque
    data:
    - objectName: postgres-admin-password
      key: postgres-admin-password
    - objectName: postgres-replication-password
      key: postgres-replication-password
    - objectName: redis-admin-password
      key: redis-admin-password

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: toss-gateway-secrets
  namespace: toss-gateway
  labels:
    app: toss-gateway
    component: secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "$(AZURE_CLIENT_ID)"
    keyvaultName: "toss-keyvault-${var.environment}"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: gateway-tls-cert
          objectType: secret
          objectVersion: ""
        - |
          objectName: oauth-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: api-key-encryption-key
          objectType: secret
          objectVersion: ""
    tenantId: "$(AZURE_TENANT_ID)"
  secretObjects:
  - secretName: toss-gateway-secrets
    type: Opaque
    data:
    - objectName: gateway-tls-cert
      key: gateway-tls-cert
    - objectName: oauth-client-secret
      key: oauth-client-secret
    - objectName: api-key-encryption-key
      key: api-key-encryption-key
