using TossErp.Stock.Domain.Entities;
using TossErp.Stock.Domain.Common;

namespace TossErp.Stock.Domain.Events;

public record ItemWebsiteSpecificationCreatedEvent(ItemWebsiteSpecification ItemWebsiteSpecification) : IDomainEvent;
public record ItemWebsiteSpecificationUpdatedEvent(ItemWebsiteSpecification ItemWebsiteSpecification) : IDomainEvent;
public record ItemWebsiteSpecificationDisplayOrderUpdatedEvent(ItemWebsiteSpecification ItemWebsiteSpecification) : IDomainEvent;
public record ItemWebsiteSpecificationDeactivatedEvent(ItemWebsiteSpecification ItemWebsiteSpecification) : IDomainEvent;
public record ItemWebsiteSpecificationActivatedEvent(ItemWebsiteSpecification ItemWebsiteSpecification) : IDomainEvent;
public record ItemWebsiteSpecificationDeletedEvent(ItemWebsiteSpecification ItemWebsiteSpecification) : IDomainEvent; 
