using TossErp.Stock.Domain.Entities;
using TossErp.Stock.Domain.Common;

namespace TossErp.Stock.Domain.Events;

public record StockEntryAdditionalCostCreatedEvent(StockEntryAdditionalCost StockEntryAdditionalCost) : IDomainEvent;
public record StockEntryAdditionalCostUpdatedEvent(StockEntryAdditionalCost StockEntryAdditionalCost) : IDomainEvent;
public record StockEntryAdditionalCostAmountUpdatedEvent(StockEntryAdditionalCost StockEntryAdditionalCost) : IDomainEvent;
public record StockEntryAdditionalCostAccountSettingsUpdatedEvent(StockEntryAdditionalCost StockEntryAdditionalCost) : IDomainEvent;
public record StockEntryAdditionalCostDisabledEvent(StockEntryAdditionalCost StockEntryAdditionalCost) : IDomainEvent;
public record StockEntryAdditionalCostEnabledEvent(StockEntryAdditionalCost StockEntryAdditionalCost) : IDomainEvent; 
