-- Initialize databases for each microservice
CREATE DATABASE IF NOT EXISTS toss_auth;
CREATE DATABASE IF NOT EXISTS toss_crm;
CREATE DATABASE IF NOT EXISTS toss_inventory;
CREATE DATABASE IF NOT EXISTS toss_accounting;
CREATE DATABASE IF NOT EXISTS toss_sales;
CREATE DATABASE IF NOT EXISTS toss_manufacturing;
CREATE DATABASE IF NOT EXISTS toss_project;
CREATE DATABASE IF NOT EXISTS toss_hr;
CREATE DATABASE IF NOT EXISTS toss_ai;
CREATE DATABASE IF NOT EXISTS toss_workflow;
CREATE DATABASE IF NOT EXISTS toss_groupbuy;
CREATE DATABASE IF NOT EXISTS toss_asset;
CREATE DATABASE IF NOT EXISTS toss_credit;
CREATE DATABASE IF NOT EXISTS toss_logistics;
CREATE DATABASE IF NOT EXISTS toss_networking;

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE toss_auth TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_crm TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_inventory TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_accounting TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_sales TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_manufacturing TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_project TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_hr TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_ai TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_workflow TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_groupbuy TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_asset TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_credit TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_logistics TO postgres;
GRANT ALL PRIVILEGES ON DATABASE toss_networking TO postgres;
