apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: toss-erp-production

namespace: toss-erp-production

resources:
- ../../base

commonLabels:
  environment: production
  app.kubernetes.io/instance: toss-erp-production

images:
- name: ghcr.io/toss-online-services/toss-erp/gateway
  newTag: v1.0.0
- name: ghcr.io/toss-online-services/toss-erp/identity
  newTag: v1.0.0
- name: ghcr.io/toss-online-services/toss-erp/ai
  newTag: v1.0.0
- name: ghcr.io/toss-online-services/toss-erp/web
  newTag: v1.0.0
- name: ghcr.io/toss-online-services/toss-erp/mobile
  newTag: v1.0.0

patchesStrategicMerge:
- replicas-patch.yaml
- resources-patch.yaml
- ingress-patch.yaml
- security-patch.yaml

configMapGenerator:
- name: toss-config-generated
  behavior: merge
  literals:
  - ASPNETCORE_ENVIRONMENT=Production
  - Logging__LogLevel__Default=Information
  - Logging__LogLevel__Microsoft=Warning
  - Logging__LogLevel__System=Warning
