apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile
spec:
  replicas: 2
