apiVersion: v1
kind: Namespace
metadata:
  name: toss-erp
  labels:
    app.kubernetes.io/name: toss-erp
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: toss-config
  namespace: toss-erp
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__DefaultConnection: "Host=postgresql;Database=toss_erp;Username=toss_user;Password=toss_password"
  EventBus__Host: "rabbitmq"
  EventBus__Username: "toss"
  EventBus__Password: "toss123"
  Redis__ConnectionString: "redis:6379"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
  Logging__LogLevel__System: "Warning"
---
apiVersion: v1
kind: Secret
metadata:
  name: toss-secrets
  namespace: toss-erp
type: Opaque
data:
  jwt-secret: dG9zcy1qd3Qtc2VjcmV0LWtleS0yMDI1 # base64 encoded
  database-password: dG9zc19wYXNzd29yZA== # base64 encoded
  rabbitmq-password: dG9zczEyMw== # base64 encoded
