namespace POS.Domain.Enums
{
    public enum UnitOfMeasure
    {
        Each,
        Kilogram,
        Gram,
        Pound,
        Ounce,
        Liter,
        Milliliter,
        Gallon,
        Quart,
        Pint,
        Meter,
        Centimeter,
        Millimeter,
        Inch,
        Foot,
        Yard,
        SquareMeter,
        SquareFoot,
        SquareYard,
        CubicMeter,
        CubicFoot,
        CubicYard,
        Box,
        Case,
        Pack,
        Bundle,
        Roll,
        Set,
        Pair,
        Dozen,
        Hundred,
        Thousand
    }
} 
