<template>
  <div class="create-return-page">
    <!-- Header -->
    <div class="page-header mb-6">
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-3xl font-bold text-gray-900 dark:text-white">
            {{ t('returns.create.title') }}
          </h1>
          <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
            {{ t('returns.create.subtitle') }}
          </p>
        </div>
        <NuxtLink
          to="/sales/returns"
          class="px-4 py-2 bg-gray-200 dark:bg-gray-700 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors flex items-center"
        >
          <Icon name="mdi:arrow-left" class="mr-2" />
          {{ t('common.back') }}
        </NuxtLink>
      </div>
    </div>

    <!-- Main Form -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
      <FormKit
        type="form"
        :actions="false"
        @submit="handleSubmit"
        v-model="formData"
      >
        <!-- Basic Information -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <FormKit
            type="select"
            name="salesInvoiceRef"
            :label="t('returns.fields.invoice')"
            :options="invoiceOptions"
            validation="required"
            :placeholder="t('returns.placeholders.selectInvoice')"
            @input="handleInvoiceSelect"
          >
            <template #prefix>
              <Icon name="mdi:file-document" class="text-gray-400" />
            </template>
          </FormKit>

          <FormKit
            type="text"
            name="returnNo"
            :label="t('returns.fields.returnNo')"
            :value="generatedReturnNo"
            :help="t('returns.help.autoGenerated')"
            disabled
          >
            <template #prefix>
              <Icon name="mdi:barcode" class="text-gray-400" />
            </template>
          </FormKit>
        </div>

        <!-- Customer Info (Auto-filled from invoice) -->
        <div v-if="selectedInvoice" class="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4 mb-6">
          <h3 class="font-semibold mb-3 flex items-center">
            <Icon name="mdi:account" class="mr-2 text-blue-600" />
            {{ t('returns.sections.customerInfo') }}
          </h3>
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
            <div>
              <span class="text-gray-600 dark:text-gray-400">{{ t('returns.fields.customerName') }}:</span>
              <span class="ml-2 font-semibold">{{ selectedInvoice.customerName }}</span>
            </div>
            <div>
              <span class="text-gray-600 dark:text-gray-400">{{ t('returns.fields.invoiceDate') }}:</span>
              <span class="ml-2 font-semibold">{{ formatDate(selectedInvoice.date) }}</span>
            </div>
            <div>
              <span class="text-gray-600 dark:text-gray-400">{{ t('returns.fields.invoiceAmount') }}:</span>
              <span class="ml-2 font-semibold">{{ formatCurrency(selectedInvoice.grandTotal) }}</span>
            </div>
          </div>
        </div>

        <!-- Return Date and Reason -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <FormKit
            type="date"
            name="returnDate"
            :label="t('returns.fields.returnDate')"
            validation="required"
            :value="todayDate"
          >
            <template #prefix>
              <Icon name="mdi:calendar" class="text-gray-400" />
            </template>
          </FormKit>

          <FormKit
            type="select"
            name="returnReason"
            :label="t('returns.fields.returnReason')"
            :options="returnReasonOptions"
            validation="required"
          >
            <template #prefix>
              <Icon name="mdi:message-text" class="text-gray-400" />
            </template>
          </FormKit>
        </div>

        <!-- Return Items -->
        <div class="mb-6">
          <h3 class="text-lg font-semibold mb-4 flex items-center">
            <Icon name="mdi:package-variant" class="mr-2 text-blue-600" />
            {{ t('returns.sections.items') }}
          </h3>

          <FormKit
            type="repeater"
            name="items"
            :label="false"
            :min="1"
            add-label="Add Item"
            #default="{ index, value }"
          >
            <div class="bg-gray-50 dark:bg-gray-900 p-4 rounded-lg mb-4">
              <div class="grid grid-cols-1 md:grid-cols-6 gap-4">
                <!-- Product -->
                <div class="md:col-span-2">
                  <FormKit
                    type="select"
                    name="productId"
                    :label="t('returns.fields.product')"
                    :options="getProductOptions()"
                    validation="required"
                    @input="handleProductSelect(index, $event)"
                  />
                </div>

                <!-- Original Qty -->
                <FormKit
                  type="number"
                  name="originalQty"
                  :label="t('returns.fields.originalQty')"
                  disabled
                  :value="value.originalQty || 0"
                />

                <!-- Return Qty -->
                <FormKit
                  type="number"
                  name="returnQty"
                  :label="t('returns.fields.returnQty')"
                  validation="required|min:0.01"
                  step="0.01"
                  min="0.01"
                  @input="calculateItemAmount(index)"
                />

                <!-- Rate -->
                <FormKit
                  type="number"
                  name="rate"
                  :label="t('returns.fields.rate')"
                  disabled
                  :value="value.rate || 0"
                />

                <!-- Amount -->
                <FormKit
                  type="number"
                  name="amount"
                  :label="t('returns.fields.amount')"
                  disabled
                  :value="calculateReturnAmount(value)"
                />
              </div>

              <!-- Item Condition & Restockable -->
              <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">
                <FormKit
                  type="select"
                  name="condition"
                  :label="t('returns.fields.condition')"
                  :options="conditionOptions"
                  validation="required"
                />

                <FormKit
                  type="checkbox"
                  name="restockable"
                  :label="t('returns.fields.restockable')"
                  :value="true"
                />

                <FormKit
                  type="text"
                  name="notes"
                  :label="t('returns.fields.itemNotes')"
                  :placeholder="t('returns.placeholders.itemNotes')"
                />
              </div>
            </div>
          </FormKit>
        </div>

        <!-- Refund Information -->
        <div class="bg-purple-50 dark:bg-purple-900/20 rounded-lg p-6 mb-6">
          <h3 class="text-lg font-semibold mb-4 flex items-center">
            <Icon name="mdi:cash-refund" class="mr-2 text-purple-600" />
            {{ t('returns.sections.refundInfo') }}
          </h3>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <FormKit
              type="select"
              name="refundMethod"
              :label="t('returns.fields.refundMethod')"
              :options="refundMethodOptions"
              validation="required"
            />

            <div class="space-y-3">
              <div class="flex justify-between text-sm">
                <span class="font-medium">{{ t('returns.totals.totalReturnAmount') }}:</span>
                <span class="font-semibold">{{ formatCurrency(totalReturnAmount) }}</span>
              </div>
              <div class="flex justify-between text-sm">
                <span class="font-medium">{{ t('returns.totals.restockingFee') }}:</span>
                <span class="font-semibold text-red-600">-{{ formatCurrency(restockingFee) }}</span>
              </div>
              <div class="flex justify-between text-lg font-bold border-t pt-3">
                <span>{{ t('returns.totals.refundAmount') }}:</span>
                <span class="text-purple-600">{{ formatCurrency(netRefundAmount) }}</span>
              </div>
            </div>
          </div>

          <div class="mt-4">
            <FormKit
              type="number"
              name="restockingFeePercent"
              :label="t('returns.fields.restockingFeePercent')"
              step="0.01"
              min="0"
              max="100"
              :value="0"
              @input="calculateRefundAmount"
            />
          </div>
        </div>

        <!-- Additional Notes -->
        <div class="mb-6">
          <FormKit
            type="textarea"
            name="notes"
            :label="t('returns.fields.notes')"
            rows="4"
            :placeholder="t('returns.placeholders.notes')"
          />
        </div>

        <!-- Form Actions -->
        <div class="flex items-center justify-end space-x-4 pt-6 border-t">
          <button
            type="button"
            @click="navigateTo('/sales/returns')"
            class="px-4 py-2 bg-gray-200 dark:bg-gray-700 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
            :disabled="loading"
          >
            {{ t('common.cancel') }}
          </button>

          <button
            type="button"
            @click="handleSaveDraft"
            class="px-4 py-2 border-2 border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors flex items-center"
            :disabled="loading"
          >
            <Icon name="mdi:content-save-outline" class="mr-2" />
            {{ t('returns.actions.saveDraft') }}
          </button>

          <button
            type="submit"
            class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center"
            :disabled="loading"
          >
            <Icon v-if="!loading" name="mdi:check" class="mr-2" />
            <Icon v-else name="mdi:loading" class="mr-2 animate-spin" />
            {{ t('returns.actions.submitReturn') }}
          </button>
        </div>
      </FormKit>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useSalesReturns } from '~/composables/useSalesReturns'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
const { createReturnFromInvoice, getReturnReasons, loading, error } = useSalesReturns()
const router = useRouter()

// Form Data
const formData = ref({
  salesInvoiceRef: null,
  returnNo: '',
  returnDate: '',
  returnReason: '',
  items: [
    {
      productId: null,
      originalQty: 0,
      returnQty: 1,
      rate: 0,
      amount: 0,
      condition: 'defective',
      restockable: true,
      notes: ''
    }
  ],
  refundMethod: 'credit_note',
  restockingFeePercent: 0,
  notes: ''
})

const selectedInvoice = ref<any>(null)

// Computed values
const todayDate = computed(() => {
  const today = new Date()
  return today.toISOString().split('T')[0]
})

const generatedReturnNo = computed(() => {
  const date = new Date()
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const random = Math.floor(Math.random() * 10000).toString().padStart(4, '0')
  return `RET-${year}${month}-${random}`
})

const totalReturnAmount = computed(() => {
  const items = formData.value.items || []
  return items.reduce((sum, item) => {
    const returnQty = parseFloat(item.returnQty || 0)
    const rate = parseFloat(item.rate || 0)
    return sum + (returnQty * rate)
  }, 0)
})

const restockingFee = computed(() => {
  const feePercent = parseFloat(formData.value.restockingFeePercent || 0)
  return totalReturnAmount.value * (feePercent / 100)
})

const netRefundAmount = computed(() => {
  return totalReturnAmount.value - restockingFee.value
})

// Options data (would be fetched from API in production)
const invoiceOptions = ref([
  { value: 'INV-202501-0001', label: 'INV-202501-0001 - Mama Dlamini (R 1,450.00)' },
  { value: 'INV-202501-0002', label: 'INV-202501-0002 - Bongani Mtshali (R 3,200.00)' },
  { value: 'INV-202501-0003', label: 'INV-202501-0003 - Thandi Ngubane (R 850.00)' }
])

const returnReasonOptions = computed(() => {
  const reasons = getReturnReasons()
  return reasons.map(r => ({ value: r.value, label: t(`returns.reasons.${r.value}`) }))
})

const refundMethodOptions = ref([
  { value: 'credit_note', label: t('returns.refundMethods.creditNote') },
  { value: 'cash', label: t('returns.refundMethods.cash') },
  { value: 'bank_transfer', label: t('returns.refundMethods.bankTransfer') },
  { value: 'original_payment', label: t('returns.refundMethods.originalPayment') }
])

const conditionOptions = ref([
  { value: 'unopened', label: t('returns.conditions.unopened') },
  { value: 'opened', label: t('returns.conditions.opened') },
  { value: 'defective', label: t('returns.conditions.defective') },
  { value: 'damaged', label: t('returns.conditions.damaged') }
])

// Mock invoice data (in production, fetch from API)
const invoiceData: Record<string, any> = {
  'INV-202501-0001': {
    customerName: 'Mama Dlamini',
    date: '2025-01-05',
    grandTotal: 1450,
    items: [
      { productId: 1, productName: 'Maize Meal 12.5kg', quantity: 5, rate: 145 },
      { productId: 2, productName: 'Cooking Oil 2L', quantity: 10, rate: 65 }
    ]
  },
  'INV-202501-0002': {
    customerName: 'Bongani Mtshali',
    date: '2025-01-06',
    grandTotal: 3200,
    items: [
      { productId: 3, productName: 'Sugar 2.5kg', quantity: 20, rate: 45 },
      { productId: 4, productName: 'Rice 5kg', quantity: 15, rate: 85 }
    ]
  }
}

// Methods
const handleInvoiceSelect = (invoiceRef: string) => {
  selectedInvoice.value = invoiceData[invoiceRef]
  if (selectedInvoice.value) {
    // Reset items to match invoice items
    formData.value.items = selectedInvoice.value.items.map((item: any) => ({
      productId: item.productId,
      productName: item.productName,
      originalQty: item.quantity,
      returnQty: 1,
      rate: item.rate,
      amount: item.rate,
      condition: 'defective',
      restockable: true,
      notes: ''
    }))
  }
}

const getProductOptions = () => {
  if (!selectedInvoice.value) return []
  return selectedInvoice.value.items.map((item: any) => ({
    value: item.productId,
    label: `${item.productName} (Qty: ${item.quantity})`
  }))
}

const handleProductSelect = (index: number, productId: number) => {
  if (!selectedInvoice.value) return
  const item = selectedInvoice.value.items.find((i: any) => i.productId === productId)
  if (item && formData.value.items[index]) {
    formData.value.items[index].originalQty = item.quantity
    formData.value.items[index].rate = item.rate
    formData.value.items[index].amount = item.rate
  }
}

const calculateItemAmount = (index: number) => {
  const item = formData.value.items[index]
  if (item) {
    const returnQty = parseFloat(item.returnQty || 0)
    const rate = parseFloat(item.rate || 0)
    item.amount = returnQty * rate
  }
  calculateRefundAmount()
}

const calculateReturnAmount = (item: any) => {
  if (!item) return 0
  const returnQty = parseFloat(item.returnQty || 0)
  const rate = parseFloat(item.rate || 0)
  return returnQty * rate
}

const calculateRefundAmount = () => {
  // Trigger reactivity by accessing computed properties
  totalReturnAmount.value
  netRefundAmount.value
}

const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('en-ZA', {
    style: 'currency',
    currency: 'ZAR'
  }).format(amount || 0)
}

const formatDate = (date: string | Date) => {
  return new Date(date).toLocaleDateString('en-ZA', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}

const handleSubmit = async () => {
  try {
    const returnData = {
      ...formData.value,
      returnNo: generatedReturnNo.value,
      status: 'pending',
      refundAmount: netRefundAmount.value
    }

    const result = await createReturnFromInvoice(
      formData.value.salesInvoiceRef || '',
      formData.value.items.map(item => ({
        productId: item.productId,
        returnQty: item.returnQty,
        returnReason: formData.value.returnReason,
        condition: item.condition,
        restockable: item.restockable
      }))
    )

    if (result) {
      alert(t('returns.messages.createSuccess'))
      await router.push('/sales/returns')
    }
  } catch (err) {
    console.error('Failed to create return:', err)
    alert(t('returns.messages.createError'))
  }
}

const handleSaveDraft = async () => {
  try {
    const returnData = {
      ...formData.value,
      returnNo: generatedReturnNo.value,
      status: 'draft',
      refundAmount: netRefundAmount.value
    }

    // In production, call API to save draft
    alert(t('returns.messages.draftSaved'))
    await router.push('/sales/returns')
  } catch (err) {
    console.error('Failed to save draft:', err)
    alert(t('returns.messages.draftError'))
  }
}

// Set initial date
onMounted(() => {
  formData.value.returnDate = todayDate.value
})
</script>

<style scoped>
.create-return-page {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem 1rem;
}
</style>
