name: TOSS MVP - Web Frontend CI

on:
  push:
    branches: [ main, feature/mvp ]
    paths:
      - 'toss-web/**'
      - '.github/workflows/ci-cd.yml'
  pull_request:
    branches: [ main, feature/mvp ]
    paths:
      - 'toss-web/**'

jobs:
  # Web Frontend Tests & Build
  web-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ./toss-web/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./toss-web
    
    - name: Run linter
      run: npm run lint
      working-directory: ./toss-web
    
    - name: Run tests
      run: npm run test
      working-directory: ./toss-web
    
    - name: Build
      run: npm run build
      working-directory: ./toss-web
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: web-build
        path: toss-web/.output/
        retention-days: 7
