name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: src/global.json

      - name: Restore & Build .NET
        run: |
          dotnet build src/eShop.sln -c Release

      - name: Run .NET Tests
        run: |
          dotnet test src/eShop.sln -c Release --no-build --logger "trx;LogFileName=tests.trx"

      - name: Export OpenAPI Specs
        run: pwsh -File scripts/export-openapi.ps1
        shell: pwsh

      - name: Upload OpenAPI Specs
        uses: actions/upload-artifact@v4
        with:
          name: openapi-specs
          path: docs/openapi/*.json

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: '**/TestResults/*.trx'

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Nuxt app
        working-directory: TossErp.Web
        run: |
          npm ci
          npm run build

      - name: Build Gateway
        run: |
          dotnet build gateway/Gateway.csproj -c Release

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container images (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          target: final
          file: gateway/Dockerfile



